package javaapplication3;
// Generated Nov 19, 2024 11:29:32 PM by Hibernate Tools 4.3.1



/**
 * Akun generated by hbm2java
 */
public class ModelAkun  implements java.io.Serializable {


     private int idAkun;
     private String nama;
     private String status;
     private String tgl;
     private int nominal;

    public ModelAkun() {
    }

    public ModelAkun(int idAkun,String nama, String status, String tgl, int nominal) {
       this.idAkun = idAkun;
       this.nama = nama;
       this.status = status;
       this.tgl = tgl;
       this.nominal = nominal;
    }
   
    public int getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(int idAkun) {
        this.idAkun = idAkun;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getTgl() {
        return this.tgl;
    }
    
    public void setTgl(String tgl) {
        this.tgl = tgl;
    }
    public int getNominal() {
        return this.nominal;
    }
    
    public void setNominal(int nominal) {
        this.nominal = nominal;
    }




}


